[meta]
name = "Speedometer"
author = "Greep"
category = "Overlay"
siteid = 207

version = "1.3.0"

[script]
dependencies = [ "VehicleState" ]
optional_dependencies = [ "CurrentEffects" ]

timeout = 0
